import api from "./axiosInstance";
export const adminAPI = {
  getDashboardStats:      ()                    => api.get("/admin/dashboard/stats"),
  getVolunteers:          (params)              => api.get("/admin/volunteers", { params }),
  getVolunteerById:       (id)                  => api.get("/admin/volunteers/" + id),
  updateVolunteerStatus:  (id, data)            => api.patch("/admin/volunteers/" + id + "/status", data),
  deleteVolunteer:        (id)                  => api.delete("/admin/volunteers/" + id),
  getTasks:               (params)              => api.get("/admin/tasks", { params }),
  createTask:             (data)                => api.post("/admin/tasks", data),
  getTaskById:            (id)                  => api.get("/admin/tasks/" + id),
  updateTask:             (id, data)            => api.put("/admin/tasks/" + id, data),
  deleteTask:             (id)                  => api.delete("/admin/tasks/" + id),
  assignVolunteers:       (id, data)            => api.post("/admin/tasks/" + id + "/assign", data),
  reviewSubmission:       (tId, sId, data)      => api.patch("/admin/tasks/" + tId + "/submissions/" + sId, data),
  getAttendance:          (params)              => api.get("/admin/attendance", { params }),
  markAttendance:         (data)                => api.post("/admin/attendance", data),
  updateAttendance:       (id, data)            => api.put("/admin/attendance/" + id, data),
  issueCertificate:       (data)                => api.post("/admin/certificates/issue", data),
  getCertificates:        ()                    => api.get("/admin/certificates"),
  revokeCertificate:      (id)                  => api.patch("/admin/certificates/" + id + "/revoke"),
  getAnnouncements:       ()                    => api.get("/admin/announcements"),
  createAnnouncement:     (data)                => api.post("/admin/announcements", data),
  deleteAnnouncement:     (id)                  => api.delete("/admin/announcements/" + id),
  exportVolunteers:       (params)              => api.get("/admin/export/volunteers",   { params, responseType: "blob" }),
  exportAttendance:       (params)              => api.get("/admin/export/attendance",   { params, responseType: "blob" }),
  exportCertificates:     (params)              => api.get("/admin/export/certificates", { params, responseType: "blob" }),
  exportSummary:          ()                    => api.get("/admin/export/summary",       { responseType: "blob" }),
};
